name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build app
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest]
        include: 
          - os: ubuntu-latest
            release_suffix: linux 
          - os: macos-latest
            release_suffix: macos
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Git checkout 
      uses: actions/checkout@v3

    - name: Install scala-cli
      uses: VirtusLab/scala-cli-setup@v1.0.5
      with: 
        power: true

    - name: Compile
      run: scala-cli compile . --build-info

    - name: Package
      run: scala-cli package . --build-info -o fs2-watch
