name: Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dist_linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git checkout 
      uses: actions/checkout@v3

    - name: Install scala-cli
      uses: VirtusLab/scala-cli-setup@v1.0.5
      with: 
        power: true

    - name: Compile
      run: scala-cli compile . --build-info

    - name: Package
      run: scala-cli package . --build-info --standalone -o fs2-watch

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,foo/*.txt"
        # bodyFile: "body.md"
