name: Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dist_linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git checkout 
      uses: actions/checkout@v3

    - name: Install scala-cli
      uses: VirtusLab/scala-cli-setup@v1.0.5
      with: 
        power: true

    - name: Compile
      run: scala-cli compile . --build-info

    - name: Package
      run: scala-cli package . --build-info --standalone -o fs2-watch

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: fs2-watch
