name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: scala-cli-setup-action
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: VirtusLab/scala-cli-setup@v1.0.5
      with: 
        power: true
    - run: scala-cli package . --build-info -o fs2-watch
