name: Deployment

on:  
  push:
    tags:
    - '*'

jobs:
  dist:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            release_suffix: linux
            upload: true
          - os: macos-latest
            release_suffix: macos
            upload: false
    runs-on: ${{ matrix.os }}

    steps:
    - name: Git checkout 
      uses: actions/checkout@v3

    - name: Install scala-cli
      uses: VirtusLab/scala-cli-setup@v1.0.5
      with: 
        power: true

    - name: Compile
      run: scala-cli compile . --build-info

    - name: Package
      run: scala-cli package . --build-info --standalone -o fs2-watch

    - name: Zip
      run: zip -rj fs2-watch-${{ matrix.release_suffix }}.zip fs2-watch

    - name: Release
      if: matrix.upload
      uses: ncipollo/release-action@v1
      with:
        artifacts: fs2-watch-${{ matrix.release_suffix }}.zip
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
